travis:
  secure:
    BINSTAR_TOKEN: GFl+o8IJ/J9xr8jxlIfyT4pyUBHT/BO6EjLtpr5FectyXMDDLzA1RbgFaaC6TVw98zMaAzwnhdBfYmvWpXVYMf1pl3q/jm5QYAram0OcmEZ93TBgbcCfje7wXDv6Y8N/+LADB90Do8Q700cwN8yOFUhOlXDEYVAQdE1SyccKOLkpAl3BW2UyQUYRd+BYPwI7uBOTj/sIfUhU2oI4eSTFCx8XvBO37/1pjZ4TovbHFXyNPUL24xTvtlNiHodLPACyWUo04WwUHVDZvJ7h4aHuxN8GG5/5PtGNwPojnJ43JKCOfy+y/sXppivFQf3uiffsuFih7EZ6XokMsfhBYjPpR9vzVApYg5zWJg0D7ishkW7gKkG+sSNzdN+wI2JzDBxbpk06BExVd/xC6N9/VLg82JIBoKRzThfKjkLOK9G2HonwCdP8SAhUSISgr/MDR2G87hSVytaRH3gCiDhpxRu60ZyvirZxEvtL8zmW3R4IZmNni1i5xtFl7zzE87ofYhiGBRwociYRRu+MmMie8g6bTdxk55jm1zGSbbtGYs+gfhRtvMuOJbL28UIv4Oby/1al3wYEZRX4qygU70Xz2yhXnOUiQ3ijD0Wdl3GqEd958Osb+piKqmNX0WW0VblqGdp+CqS9dDEyQ51rivONGfZV3FS2ghNki6XhzQ06uv9hVss=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
